# Generated by Django 5.2.8 on 2025-11-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='problemas/'),
        ),
    ]
